### ISSUE TITLE
New DB Support

### ISSUE THREAD

**Issue by raptor235** [snapperben/gulp-mysql-command-file-processor#4]
Also supporting a new db creation and drop of existing db would be great :)

**Comment by snapperben** [comment]
It does that currently.  Here is and excerpt from the beginning of my create schema script which drops an existing database and re-creates it.
Make sure you use version 1.0.3 as I fixed it so it ignored ';' in comments and copes with escaped characters .......
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

---

-- Schema new_db

---

DROP SCHEMA IF EXISTS `new_db` ;

---

-- Schema new_vmf

---

CREATE SCHEMA IF NOT EXISTS `new_db` DEFAULT CHARACTER SET latin1 ;
USE `new_db` ;

---

-- Table `new_db`.`user`

---

DROP TABLE IF EXISTS `new_db`.`user` ;

CREATE TABLE IF NOT EXISTS `new_db`.`user` (......................
