### ISSUE TITLE
USE `db_name`

### ISSUE THREAD

**Issue by manatax** [snapperben/gulp-mysql-command-file-processor#5]
It would be great if you include the option to select a database by name.
It's just a matter of adding the 'database' property to the createConnection method call.

**Comment by snapperben** [comment]
As far as I'm aware you cannot specify a database name when connecting to a MySQL server, you can only specify a username to log in as. It is possible to specify a default schema for that user to use though.
If you look at the last example (Data population SQL) in tha package description, the database (or schema in MySQL terms) is set by the term "USE <db_name>;" which means all subsequent SQL statements would use that database/schema.
If you wanted to use different databases/schemas in the same file then you wouls have to use two or more USE statements or refer to a table  as <db_name>.<table_name>.
Another alternative is to set up several users, each with a different default schema/database. That would then mean that you effectively select the database by choosing the user you connect to MySQL as.
I hope that answers your question....if not please feel free to ask for a clarification. It's nearly 1 AM here in the UK so I'll get back to you in 8 hours or so.

Cheers

**Comment by manatax** [comment]
https://www.npmjs.com/package/mysql#introduction
the database property let's you select the schema.

## 

Ezequiel Rodrigué

**Comment by snapperben** [comment]
I'll investigate that

**Comment by snapperben** [comment]
This has now been fixed...please check

Cheers

Ben
