### ISSUE TITLE
Comments are not supported

### ISSUE THREAD

**Issue by iseus** [snapperben/gulp-mysql-command-file-processor#6]
Hi,

I'd like to test deployable .sql schema which contains comments also. It would be a great extension to your module if you add the 3 basic comment type:

From a `#` or `--` to the end of the line, and comment blocks between `/*` and `*/`.

Thanks

**Comment by snapperben** [comment]
Hi,

As I submit all lines to MySql as they appear in the file all comments
should be supported.

If you're having a problem with comments it could be that one contains the
command delimiter ';'. I have just checked the code and any character
(including ';') can be escaped with '\' such that it will be ignored. I had
exactly that problem and I escaped or removed al my semi colons

If that doesn't solve the problem then please come back to me

Cheers

Ben

**Comment by iseus** [comment]
> If you're having a problem with comments it could be that one contains the
> command delimiter ';'.

Yes it contains because I commented out actually valid queries.

You are right btw (it was my mistake by syntax) in case when you comment only single lines, with for example `-- DROP TABLE [...];` or `# DROP TABLE [...];`. I forgot the space between `#` and the statement.

In the other hand, on multi line comments you should ignore the `;` inside the command blocks, in that case it would work perfectly without breaking your queries.

**Comment by snapperben** [comment]
I'm afraid that at the moment it doesn't have knowledge of comments....it
only looks at the actual characters by themselves.
I might look at doing that but at the moment I'm really focused on other
development and can't do anything.

I will get back to you in the next few weeks

Thanks for using it...I'm really stoke that others have found this useful!

Cheers

Ben

**Comment by iseus** [comment]
I use it because good enough not to write my own, and the only solution available on npm. I'll make an addition for the comment blocks and make a pull request this weekend.
