### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by iseus** [snapperben/gulp-mysql-command-file-processor#8]
It would be nice if you update the npm package also.

Here is one of your fork with some clever additions:
[strickdj](https://github.com/strickdj/gulp-mysql-command-file-processor)

Including this package.json and moving the js file to the root folder is a good idea because this module doesn't have any library or included file.

Steve

**Comment by snapperben** [comment]
Steve,
I have updated the NPM package to 1.0.4 I am a complete numpty at NPM/Gist
(my background is C++ server side on banking systems) so I hope I haven't
screwed it up. I will look at moving the index.js file location in Git as
suggested soon

cheers

Ben

**Comment by iseus** [comment]
Thanks, I had to make some more modifications because I found a bug in the comment block handling. Also I'll make some tests and changes for stored procedure handling because developers usually changes the delimiter, which means sending a command after every `;` will cause errors also.
